services:
  vosk-api:
    build: .
    ports:
      - "2700:2700"
    volumes:
      - .:/opt/vosk/
      - vosk-models:/opt/vosk/models
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    networks:
      - ai-buddy

networks:
  ai-buddy:
    driver: bridge

volumes:
  vosk-models:
    driver: local
